name: CI - Training Tracker

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./backend/MyService.Api/MyService.Api.csproj

      - name: Build
        run: dotnet build ./backend/MyService.Api/MyService.Api.csproj --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test ./backend/MyService.Tests/MyService.Tests.csproj --no-build --verbosity normal
